name: SFTP Deploy with LFS support

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Pull LFS objects
        run: git lfs pull

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./*
          remote_path: ${{ secrets.FTP_DIRECTORY }}
          sftp_only: true